### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emin4516** [mikhailsdv/guess-the-age-bot#1]
![Screenshot_2022-05-24-01-15-31-335_com android chrome](https://user-images.githubusercontent.com/70646344/169910686-ebeab24e-df15-454d-991c-942cd0121973.jpg)

**Comment by mikhailsdv** [comment]
Make shure you use right names of photos. The first number must be the age.
![image](https://user-images.githubusercontent.com/39059391/169911338-32bb67bc-061d-4aa8-a2c2-0476343a72cd.png)
